# Generated by Django 5.2.9 on 2026-08-11 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoai', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaintanalysis',
            options={'ordering': ('-priority_index',), 'verbose_name': 'GeoAI tahlil natijasi', 'verbose_name_plural': 'GeoAI tahlil natijalari'},
        ),
    ]
