# Generated by Django 5.2.9 on 2026-08-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_report_work_evidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportworkevidence',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
